### ISSUE TITLE
Fix Afraid of the Dark

### ISSUE THREAD

**Issue by barendventer** [seriouslysean/DoD_90sKid#3]
Replace:

```
<targetHitEffectBuff percentage="10" name="Afraid of the Dark" />
```

With:

```
<targetHitEffectBuff percentage="10" name="Afraid of the Dark"  after="1"/>
```

Without this the targets will never sleep, because they'll be attacked immediately after the sleep status is added.

**Comment by seriouslysean** [comment]
Fixed in c7dd8676dda71cdd2eac3c9628760d6f98799a9b
